defmodule Helpdesk.Repo.Migrations.InitHealth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:patients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :gender, :text, null: false
      add :age, :bigint, null: false
      add :facility_id, :uuid, null: false
      add :status, :text, null: false, default: "admitted"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:facility, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:patients) do
      modify :facility_id,
             references(:facility,
               column: :id,
               name: "patients_facility_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:facility) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :name, :text, null: false
      add :county, :text, null: false
      add :subcounty, :text, null: false
    end
  end

  def down do
    alter table(:facility) do
      remove :subcounty
      remove :county
      remove :name
      remove :updated_at
      remove :created_at
    end

    drop constraint(:patients, "patients_facility_id_fkey")

    alter table(:patients) do
      modify :facility_id, :uuid
    end

    drop table(:facility)

    drop table(:patients)
  end
end
